### ISSUE TITLE
Blueprinting

### ISSUE THREAD

**Issue by lucasho22** [NinjaBreadLord/super-duper-bassoons#11]
Create a blueprint for routing.

> [Daniel's Commit](https://github.com/NinjaBreadLord/super-duper-bassoons/commit/c52b85abdea930a051fd65bd053a2339456c76db)

- [x] Create blueprint for Lucas
- [x] Create blueprint for Daniel
- [x] Create blueprint for Jun
- [x] Create blueprint for Rithwikh
- [x] Create blueprint for everitT
- [x] Create blueprint for API

**Comment by dtsivkovski** [comment]
Completed
> @lucasho22 @guapbeast @peacekeeper6 @NinjaBreadLord @dtsivkovski

To use the blueprinting properly, go to the /routes directory and find your python file, and then add any of your new routes into that file. Make sure to use the correct app_**name**.route template, otherwise it won't work correctly.
